import {
  UserProfile,
  Group,
  GroupMember,
  Task,
  TaskParticipant,
  ActivityFeedItem,
  Challenge,
  NotificationItem,
  MemberAnalytics,
  SpotifyTrack,
  UserMusicPresence,
  FocusStation,
  FocusRoom,
} from "@/types";
import { DEMO_GROUP_ID, CURRENT_USER_ID, DEMO_INVITE_CODE } from "./constants";

export const INITIAL_USERS: Record<string, UserProfile> = {
  "user-nova": {
    id: "user-nova",
    displayName: "Nova Vance",
    username: "novavance",
    email: "nova@sync.dev",
    photoURL: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    timezone: "America/New_York",
    bio: "Building distributed systems & prepping for SWE interviews.",
    githubUsername: "novavance",
    leetcodeUsername: "novacodes",
    totalXP: 3920,
    level: 14,
    streak: {
      current: 18,
      longest: 24,
      lastActiveDate: new Date().toISOString().split("T")[0],
    },
    createdAt: "2026-01-10T08:00:00Z",
  },
  "user-rahul": {
    id: "user-rahul",
    displayName: "Rahul Sharma",
    username: "rahulsharma",
    email: "rahul@sync.dev",
    photoURL: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    timezone: "America/Chicago",
    bio: "Systems hacker. Rust & Go enthusiast.",
    githubUsername: "rahulsh",
    leetcodeUsername: "rahul_codes",
    totalXP: 3480,
    level: 13,
    streak: {
      current: 14,
      longest: 19,
      lastActiveDate: new Date().toISOString().split("T")[0],
    },
    createdAt: "2026-01-12T09:30:00Z",
  },
  "user-arun": {
    id: "user-arun",
    displayName: "Arun Patel",
    username: "arunpatel",
    email: "arun@sync.dev",
    photoURL: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    timezone: "America/Los_Angeles",
    bio: "Full stack TypeScript & UI perfectionist.",
    githubUsername: "arunp",
    leetcodeUsername: "arun_algo",
    totalXP: 2750,
    level: 11,
    streak: {
      current: 9,
      longest: 15,
      lastActiveDate: new Date().toISOString().split("T")[0],
    },
    createdAt: "2026-01-15T11:00:00Z",
  },
  "user-karthik": {
    id: "user-karthik",
    displayName: "Karthik Raja",
    username: "karthikraja",
    email: "karthik@sync.dev",
    photoURL: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    timezone: "America/Toronto",
    bio: "ML algorithms & backend engineering.",
    githubUsername: "karthikr",
    leetcodeUsername: "kraja_dev",
    totalXP: 2340,
    level: 10,
    streak: {
      current: 6,
      longest: 12,
      lastActiveDate: new Date().toISOString().split("T")[0],
    },
    createdAt: "2026-01-18T14:20:00Z",
  },
};

export const INITIAL_GROUP: Group = {
  id: DEMO_GROUP_ID,
  name: "Founders Squad",
  description: "Private engineering & interview prep sprint crew.",
  imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80",
  ownerId: "user-nova",
  inviteCode: DEMO_INVITE_CODE,
  memberCount: 4,
  createdAt: "2026-01-10T08:00:00Z",
};

export const INITIAL_GROUP_MEMBERS: GroupMember[] = [
  {
    userId: "user-nova",
    groupId: DEMO_GROUP_ID,
    role: "owner",
    joinedAt: "2026-01-10T08:00:00Z",
    userSnapshot: {
      displayName: "Nova Vance",
      username: "novavance",
      photoURL: INITIAL_USERS["user-nova"].photoURL,
      totalXP: 3920,
      level: 14,
      streak: 18,
      rank: 1,
      weeklyXP: 510,
      monthlyXP: 1840,
      tasksCompleted: 42,
    },
  },
  {
    userId: "user-rahul",
    groupId: DEMO_GROUP_ID,
    role: "admin",
    joinedAt: "2026-01-12T09:30:00Z",
    userSnapshot: {
      displayName: "Rahul Sharma",
      username: "rahulsharma",
      photoURL: INITIAL_USERS["user-rahul"].photoURL,
      totalXP: 3480,
      level: 13,
      streak: 14,
      rank: 2,
      weeklyXP: 440,
      monthlyXP: 1620,
      tasksCompleted: 38,
    },
  },
  {
    userId: "user-arun",
    groupId: DEMO_GROUP_ID,
    role: "member",
    joinedAt: "2026-01-15T11:00:00Z",
    userSnapshot: {
      displayName: "Arun Patel",
      username: "arunpatel",
      photoURL: INITIAL_USERS["user-arun"].photoURL,
      totalXP: 2750,
      level: 11,
      streak: 9,
      rank: 3,
      weeklyXP: 380,
      monthlyXP: 1210,
      tasksCompleted: 29,
    },
  },
  {
    userId: "user-karthik",
    groupId: DEMO_GROUP_ID,
    role: "member",
    joinedAt: "2026-01-18T14:20:00Z",
    userSnapshot: {
      displayName: "Karthik Raja",
      username: "karthikraja",
      photoURL: INITIAL_USERS["user-karthik"].photoURL,
      totalXP: 2340,
      level: 10,
      streak: 6,
      rank: 4,
      weeklyXP: 290,
      monthlyXP: 980,
      tasksCompleted: 24,
    },
  },
];

const todayStr = new Date().toISOString().split("T")[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split("T")[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0];

export const INITIAL_TASKS: Task[] = [
  {
    id: "task-etm-prep",
    groupId: DEMO_GROUP_ID,
    creatorId: "user-rahul",
    creatorName: "Rahul Sharma",
    title: "ETM Test Preparation & High-Yield Review",
    notes: "Review Chapters 3-7: Finite Automata, Context Free Grammars, and Turing Decidability proofs. Complete past paper 2024.",
    scheduledDate: todayStr,
    scheduledTime: "14:00",
    deadline: `${todayStr}T20:00:00Z`,
    repeat: "never",
    visibility: "group",
    assignedParticipantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    xpReward: 20,
    priority: "high",
    isSquadComplete: false,
    createdAt: "2026-09-10T10:00:00Z",
  },
  {
    id: "task-leetcode-daily",
    groupId: DEMO_GROUP_ID,
    creatorId: "user-nova",
    creatorName: "Nova Vance",
    title: "LeetCode Daily: Subarray Sum Equals K",
    notes: "Implement with Hash Map prefix sum technique. Aim for O(n) time and O(n) space.",
    scheduledDate: todayStr,
    scheduledTime: "10:30",
    deadline: `${todayStr}T23:59:59Z`,
    repeat: "daily",
    visibility: "only_me",
    assignedParticipantIds: ["user-nova"],
    xpReward: 20,
    priority: "medium",
    isSquadComplete: true,
    createdAt: "2026-09-11T07:00:00Z",
  },
  {
    id: "task-dbms-assignment",
    groupId: DEMO_GROUP_ID,
    creatorId: "user-nova",
    creatorName: "Nova Vance",
    title: "DBMS Assignment: 3NF & BCNF Normalization",
    notes: "Decomposition algorithm exercises and SQL queries verification.",
    scheduledDate: todayStr,
    scheduledTime: "18:00",
    deadline: `${todayStr}T21:00:00Z`,
    repeat: "never",
    visibility: "group",
    assignedParticipantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    xpReward: 20,
    priority: "high",
    isSquadComplete: false,
    createdAt: "2026-09-10T15:00:00Z",
  },
  {
    id: "task-sys-arch",
    groupId: DEMO_GROUP_ID,
    creatorId: "user-arun",
    creatorName: "Arun Patel",
    title: "System Architecture: Worker Queue & Redis Backoff",
    notes: "Design resilient job processing pipeline for background notifications.",
    scheduledDate: tomorrow,
    scheduledTime: "11:00",
    repeat: "never",
    visibility: "selected",
    assignedParticipantIds: ["user-nova", "user-rahul", "user-arun"],
    xpReward: 20,
    priority: "medium",
    isSquadComplete: false,
    createdAt: "2026-09-11T08:00:00Z",
  },
  {
    id: "task-distributed-notes",
    groupId: DEMO_GROUP_ID,
    creatorId: "user-karthik",
    creatorName: "Karthik Raja",
    title: "Raft Consensus Protocol Study Notes",
    notes: "Leader election, log replication, and safety invariants summary.",
    scheduledDate: tomorrow,
    scheduledTime: "16:00",
    repeat: "weekly",
    visibility: "group",
    assignedParticipantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    xpReward: 20,
    priority: "low",
    isSquadComplete: false,
    createdAt: "2026-09-11T08:30:00Z",
  },
  {
    id: "task-yesterday-mock",
    groupId: DEMO_GROUP_ID,
    creatorId: "user-rahul",
    creatorName: "Rahul Sharma",
    title: "CS301 Mock Exam 1 (Algorithms & Data Structures)",
    notes: "Timed 90-minute problem set on Dynamic Programming and Graphs.",
    scheduledDate: yesterday,
    scheduledTime: "15:00",
    repeat: "never",
    visibility: "group",
    assignedParticipantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    xpReward: 20,
    priority: "high",
    isSquadComplete: true,
    createdAt: "2026-09-09T12:00:00Z",
  },
];

export const INITIAL_PARTICIPANTS: TaskParticipant[] = [
  // ETM Prep: Nova & Rahul completed, Arun & Karthik pending
  {
    userId: "user-nova",
    taskId: "task-etm-prep",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-11T08:45:00Z",
  },
  {
    userId: "user-rahul",
    taskId: "task-etm-prep",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-11T09:15:00Z",
  },
  {
    userId: "user-arun",
    taskId: "task-etm-prep",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-karthik",
    taskId: "task-etm-prep",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },

  // LeetCode Daily: Nova completed
  {
    userId: "user-nova",
    taskId: "task-leetcode-daily",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-11T07:40:00Z",
  },

  // DBMS Assignment: Rahul completed, others in progress
  {
    userId: "user-nova",
    taskId: "task-dbms-assignment",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-rahul",
    taskId: "task-dbms-assignment",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-11T09:00:00Z",
  },
  {
    userId: "user-arun",
    taskId: "task-dbms-assignment",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-karthik",
    taskId: "task-dbms-assignment",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },

  // System Arch: Arun completed, Nova and Rahul in progress
  {
    userId: "user-nova",
    taskId: "task-sys-arch",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-rahul",
    taskId: "task-sys-arch",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-arun",
    taskId: "task-sys-arch",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-11T09:10:00Z",
  },

  // Raft Consensus: all pending
  {
    userId: "user-nova",
    taskId: "task-distributed-notes",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-rahul",
    taskId: "task-distributed-notes",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-arun",
    taskId: "task-distributed-notes",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },
  {
    userId: "user-karthik",
    taskId: "task-distributed-notes",
    groupId: DEMO_GROUP_ID,
    completed: false,
    completedAt: null,
  },

  // Yesterday mock: all 4 completed (Squad complete!)
  {
    userId: "user-nova",
    taskId: "task-yesterday-mock",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-10T16:20:00Z",
  },
  {
    userId: "user-rahul",
    taskId: "task-yesterday-mock",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-10T16:15:00Z",
  },
  {
    userId: "user-arun",
    taskId: "task-yesterday-mock",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-10T16:45:00Z",
  },
  {
    userId: "user-karthik",
    taskId: "task-yesterday-mock",
    groupId: DEMO_GROUP_ID,
    completed: true,
    completedAt: "2026-09-10T17:00:00Z",
  },
];

export const INITIAL_ACTIVITIES: ActivityFeedItem[] = [
  {
    id: "act-1",
    groupId: DEMO_GROUP_ID,
    userId: "user-rahul",
    userName: "Rahul Sharma",
    userPhotoURL: INITIAL_USERS["user-rahul"].photoURL,
    type: "task_completed",
    description: "completed DBMS Assignment: 3NF & BCNF Normalization",
    xpAwarded: 30, // 20 + 10 early bonus
    timestamp: "12 minutes ago",
  },
  {
    id: "act-2",
    groupId: DEMO_GROUP_ID,
    userId: "user-nova",
    userName: "Nova Vance",
    userPhotoURL: INITIAL_USERS["user-nova"].photoURL,
    type: "leetcode_solved",
    description: "solved 2 LeetCode problems (Medium) · Prefix Sums",
    xpAwarded: 50,
    timestamp: "45 minutes ago",
  },
  {
    id: "act-3",
    groupId: DEMO_GROUP_ID,
    userId: "user-arun",
    userName: "Arun Patel",
    userPhotoURL: INITIAL_USERS["user-arun"].photoURL,
    type: "task_completed",
    description: "completed System Architecture: Worker Queue & Redis Backoff",
    xpAwarded: 20,
    timestamp: "1 hour ago",
  },
  {
    id: "act-4",
    groupId: DEMO_GROUP_ID,
    userId: "user-nova",
    userName: "Nova Vance",
    userPhotoURL: INITIAL_USERS["user-nova"].photoURL,
    type: "task_completed",
    description: "completed ETM Test Preparation & High-Yield Review",
    xpAwarded: 30,
    timestamp: "2 hours ago",
  },
  {
    id: "act-5",
    groupId: DEMO_GROUP_ID,
    userId: "user-karthik",
    userName: "Karthik Raja",
    userPhotoURL: INITIAL_USERS["user-karthik"].photoURL,
    type: "github_push",
    description: "pushed 4 commits to sync-core (Raft election branch)",
    xpAwarded: 8,
    timestamp: "3 hours ago",
  },
  {
    id: "act-6",
    groupId: DEMO_GROUP_ID,
    userId: "user-nova",
    userName: "Founders Squad",
    userPhotoURL: INITIAL_GROUP.imageUrl!,
    type: "squad_task_completed",
    description: "Squad complete: CS301 Mock Exam 1 · All 4 members completed!",
    xpAwarded: 30,
    timestamp: "Yesterday at 5:00 PM",
  },
  {
    id: "act-7",
    groupId: DEMO_GROUP_ID,
    userId: "user-nova",
    userName: "Nova Vance",
    userPhotoURL: INITIAL_USERS["user-nova"].photoURL,
    type: "streak_milestone",
    description: "reached an 18-day active streak milestone 🔥",
    xpAwarded: 5,
    timestamp: "Yesterday",
  },
];

export const INITIAL_CHALLENGES: Challenge[] = [
  {
    id: "chal-leetcode-sprint",
    groupId: DEMO_GROUP_ID,
    title: "September LeetCode Sprint",
    description: "Solve 40 LeetCode problems before month end. Med/Hard counts double.",
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    metric: "leetcode_solved",
    targetValue: 40,
    xpReward: 100,
    participantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    status: "active",
    currentProgress: {
      "user-nova": 28,
      "user-rahul": 31,
      "user-arun": 18,
      "user-karthik": 14,
    },
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "chal-github-streak",
    groupId: DEMO_GROUP_ID,
    title: "Clean Green GitHub Sprint",
    description: "Hit 50 git contributions across open source and project repositories.",
    startDate: "2026-09-01",
    endDate: "2026-09-30",
    metric: "github_contributions",
    targetValue: 50,
    xpReward: 100,
    participantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    status: "active",
    currentProgress: {
      "user-nova": 38,
      "user-rahul": 44,
      "user-arun": 22,
      "user-karthik": 29,
    },
    createdAt: "2026-09-01T00:00:00Z",
  },
  {
    id: "chal-august-grind",
    groupId: DEMO_GROUP_ID,
    title: "August Algorithm Grindathon",
    description: "First member to complete 60 algorithm problems in August.",
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    metric: "tasks_completed",
    targetValue: 60,
    xpReward: 100,
    participantIds: ["user-nova", "user-rahul", "user-arun", "user-karthik"],
    status: "completed",
    winnerId: "user-rahul",
    currentProgress: {
      "user-nova": 58,
      "user-rahul": 60,
      "user-arun": 42,
      "user-karthik": 36,
    },
    createdAt: "2026-08-01T00:00:00Z",
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "user-nova",
    groupId: DEMO_GROUP_ID,
    title: "Upcoming Task Reminder",
    message: "DBMS Assignment: 3NF & BCNF Normalization is scheduled for 6:00 PM.",
    type: "task_reminder",
    read: false,
    createdAt: "10 minutes ago",
    link: "/schedule",
  },
  {
    id: "notif-2",
    userId: "user-nova",
    groupId: DEMO_GROUP_ID,
    title: "Shared Task Progress",
    message: "Rahul Sharma completed 'ETM Test Preparation'. 2 of 4 participants finished.",
    type: "squad_completion",
    read: false,
    createdAt: "25 minutes ago",
    link: "/schedule",
  },
  {
    id: "notif-3",
    userId: "user-nova",
    groupId: DEMO_GROUP_ID,
    title: "Challenge Update",
    message: "Rahul gained the #1 spot in 'September LeetCode Sprint' (31/40).",
    type: "challenge_update",
    read: true,
    createdAt: "2 hours ago",
    link: "/challenges",
  },
  {
    id: "notif-4",
    userId: "user-nova",
    groupId: DEMO_GROUP_ID,
    title: "Rank Movement",
    message: "You climbed to Rank #1 on the Founders Squad leaderboard! (+1)",
    type: "rank_change",
    read: true,
    createdAt: "Yesterday",
    link: "/leaderboard",
  },
];

export const MEMBERS_ANALYTICS: Record<string, MemberAnalytics> = {
  "user-nova": {
    userId: "user-nova",
    displayName: "Nova Vance",
    username: "novavance",
    photoURL: INITIAL_USERS["user-nova"].photoURL,
    level: 14,
    totalXP: 3920,
    weeklyXP: 510,
    monthlyXP: 1840,
    rank: 1,
    rankMovement: 1,
    streak: 18,
    tasksCompleted: 42,
    consistencyScore: 96,
    leetcode: {
      username: "novacodes",
      totalSolved: 142,
      easy: 68,
      medium: 55,
      hard: 19,
      ranking: 48210,
      recentSubmissions: [
        { title: "Subarray Sum Equals K", timestamp: "Today", difficulty: "Medium" },
        { title: "Longest Consecutive Sequence", timestamp: "Yesterday", difficulty: "Medium" },
        { title: "Trapping Rain Water", timestamp: "2 days ago", difficulty: "Hard" },
      ],
    },
    github: {
      username: "novavance",
      totalContributionsYear: 284,
      currentStreak: 18,
      contributionsByWeek: Array.from({ length: 16 }, (_, i) =>
        Array.from({ length: 7 }, (_, j) => ((i * 3 + j * 5) % 6 > 2 ? ((i + j) % 4) + 1 : 0))
      ),
      recentCommits: [
        { repo: "novavance/sync-app", message: "feat(scheduler): add participant completion hook", timestamp: "1 hour ago" },
        { repo: "novavance/algo-vault", message: "solution: prefix sum hashmap pattern", timestamp: "3 hours ago" },
      ],
    },
    xpHistory7Days: [
      { date: "Fri", xp: 60, tasks: 3 },
      { date: "Sat", xp: 45, tasks: 2 },
      { date: "Sun", xp: 75, tasks: 3 },
      { date: "Mon", xp: 90, tasks: 4 },
      { date: "Tue", xp: 65, tasks: 3 },
      { date: "Wed", xp: 85, tasks: 4 },
      { date: "Thu", xp: 90, tasks: 3 },
    ],
    xpHistory30Days: [
      { date: "Day 1", xp: 40 },
      { date: "Day 5", xp: 120 },
      { date: "Day 10", xp: 260 },
      { date: "Day 15", xp: 380 },
      { date: "Day 20", xp: 490 },
      { date: "Day 25", xp: 680 },
      { date: "Day 30", xp: 920 },
    ],
  },
  "user-rahul": {
    userId: "user-rahul",
    displayName: "Rahul Sharma",
    username: "rahulsharma",
    photoURL: INITIAL_USERS["user-rahul"].photoURL,
    level: 13,
    totalXP: 3480,
    weeklyXP: 440,
    monthlyXP: 1620,
    rank: 2,
    rankMovement: -1,
    streak: 14,
    tasksCompleted: 38,
    consistencyScore: 91,
    leetcode: {
      username: "rahul_codes",
      totalSolved: 165,
      easy: 82,
      medium: 65,
      hard: 18,
      ranking: 42100,
      recentSubmissions: [
        { title: "Course Schedule II", timestamp: "Today", difficulty: "Medium" },
        { title: "Word Break", timestamp: "Yesterday", difficulty: "Medium" },
      ],
    },
    github: {
      username: "rahulsh",
      totalContributionsYear: 312,
      currentStreak: 14,
      contributionsByWeek: Array.from({ length: 16 }, (_, i) =>
        Array.from({ length: 7 }, (_, j) => ((i * 2 + j * 4) % 5 > 2 ? ((i + j) % 3) + 1 : 0))
      ),
      recentCommits: [
        { repo: "rahulsh/raft-rs", message: "implement vote request RPC handler", timestamp: "2 hours ago" },
      ],
    },
    xpHistory7Days: [
      { date: "Fri", xp: 50, tasks: 2 },
      { date: "Sat", xp: 70, tasks: 3 },
      { date: "Sun", xp: 40, tasks: 2 },
      { date: "Mon", xp: 85, tasks: 4 },
      { date: "Tue", xp: 60, tasks: 3 },
      { date: "Wed", xp: 75, tasks: 3 },
      { date: "Thu", xp: 60, tasks: 2 },
    ],
    xpHistory30Days: [
      { date: "Day 1", xp: 50 },
      { date: "Day 5", xp: 140 },
      { date: "Day 10", xp: 290 },
      { date: "Day 15", xp: 410 },
      { date: "Day 20", xp: 550 },
      { date: "Day 25", xp: 710 },
      { date: "Day 30", xp: 840 },
    ],
  },
  "user-arun": {
    userId: "user-arun",
    displayName: "Arun Patel",
    username: "arunpatel",
    photoURL: INITIAL_USERS["user-arun"].photoURL,
    level: 11,
    totalXP: 2750,
    weeklyXP: 380,
    monthlyXP: 1210,
    rank: 3,
    rankMovement: 0,
    streak: 9,
    tasksCompleted: 29,
    consistencyScore: 84,
    leetcode: {
      username: "arun_algo",
      totalSolved: 98,
      easy: 52,
      medium: 38,
      hard: 8,
      ranking: 89400,
      recentSubmissions: [
        { title: "Binary Tree Level Order Traversal", timestamp: "2 days ago", difficulty: "Medium" },
      ],
    },
    github: {
      username: "arunp",
      totalContributionsYear: 145,
      currentStreak: 9,
      contributionsByWeek: Array.from({ length: 16 }, (_, i) =>
        Array.from({ length: 7 }, (_, j) => ((i * 4 + j) % 7 > 3 ? 2 : 0))
      ),
      recentCommits: [
        { repo: "arunp/queue-worker", message: "add exponential backoff strategy", timestamp: "Yesterday" },
      ],
    },
    xpHistory7Days: [
      { date: "Fri", xp: 40, tasks: 2 },
      { date: "Sat", xp: 30, tasks: 1 },
      { date: "Sun", xp: 50, tasks: 2 },
      { date: "Mon", xp: 60, tasks: 3 },
      { date: "Tue", xp: 70, tasks: 3 },
      { date: "Wed", xp: 65, tasks: 3 },
      { date: "Thu", xp: 65, tasks: 3 },
    ],
    xpHistory30Days: [
      { date: "Day 1", xp: 30 },
      { date: "Day 5", xp: 90 },
      { date: "Day 10", xp: 190 },
      { date: "Day 15", xp: 310 },
      { date: "Day 20", xp: 420 },
      { date: "Day 25", xp: 530 },
      { date: "Day 30", xp: 650 },
    ],
  },
  "user-karthik": {
    userId: "user-karthik",
    displayName: "Karthik Raja",
    username: "karthikraja",
    photoURL: INITIAL_USERS["user-karthik"].photoURL,
    level: 10,
    totalXP: 2340,
    weeklyXP: 290,
    monthlyXP: 980,
    rank: 4,
    rankMovement: 0,
    streak: 6,
    tasksCompleted: 24,
    consistencyScore: 79,
    leetcode: {
      username: "kraja_dev",
      totalSolved: 82,
      easy: 48,
      medium: 28,
      hard: 6,
      ranking: 104500,
      recentSubmissions: [
        { title: "Number of Islands", timestamp: "3 days ago", difficulty: "Medium" },
      ],
    },
    github: {
      username: "karthikr",
      totalContributionsYear: 190,
      currentStreak: 6,
      contributionsByWeek: Array.from({ length: 16 }, (_, i) =>
        Array.from({ length: 7 }, (_, j) => ((i * 3 + j * 2) % 6 > 3 ? 1 : 0))
      ),
      recentCommits: [
        { repo: "karthikr/consensus-study", message: "add raft log replication diagrams", timestamp: "Yesterday" },
      ],
    },
    xpHistory7Days: [
      { date: "Fri", xp: 20, tasks: 1 },
      { date: "Sat", xp: 35, tasks: 2 },
      { date: "Sun", xp: 30, tasks: 1 },
      { date: "Mon", xp: 50, tasks: 2 },
      { date: "Tue", xp: 45, tasks: 2 },
      { date: "Wed", xp: 50, tasks: 2 },
      { date: "Thu", xp: 60, tasks: 3 },
    ],
    xpHistory30Days: [
      { date: "Day 1", xp: 20 },
      { date: "Day 5", xp: 70 },
      { date: "Day 10", xp: 140 },
      { date: "Day 15", xp: 230 },
      { date: "Day 20", xp: 320 },
      { date: "Day 25", xp: 420 },
      { date: "Day 30", xp: 510 },
    ],
  },
};

export const DEFAULT_MEET_URL =
  process.env.NEXT_PUBLIC_DEFAULT_MEET_URL || "https://meet.google.com/syn-squad-prg";

export const INITIAL_SPOTIFY_PRESENCES: Record<string, UserMusicPresence> = {
  "user-nova": {
    userId: "user-nova",
    isPlaying: true,
    track: {
      id: "track-nova-1",
      title: "Time",
      artist: "Hans Zimmer",
      album: "Inception (Original Motion Picture Soundtrack)",
      albumArt: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/track/6ZFbIcPtKiWio044Gh53W8",
      embedUri: "https://open.spotify.com/embed/track/6ZFbIcPtKiWio044Gh53W8?utm_source=generator&theme=0",
      streamUrl: "https://stream.radioparadise.com/mellow-128",
      durationMs: 275000,
      genre: "Cinematic / Deep Work",
    },
    progressMs: 142000,
    lastUpdated: new Date().toISOString(),
  },
  "user-rahul": {
    userId: "user-rahul",
    isPlaying: true,
    track: {
      id: "track-rahul-1",
      title: "Nightcall",
      artist: "Kavinsky",
      album: "OutRun",
      albumArt: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/track/0u6Jd75mCsd487N0B84G2y",
      embedUri: "https://open.spotify.com/embed/track/0u6Jd75mCsd487N0B84G2y?utm_source=generator&theme=0",
      streamUrl: "https://ilm.stream35.radiohost.de/ilm_ilovesugarradio_mp3-192",
      durationMs: 259000,
      genre: "Synthwave Coding",
    },
    progressMs: 89000,
    lastUpdated: new Date().toISOString(),
  },
  "user-arun": {
    userId: "user-arun",
    isPlaying: true,
    track: {
      id: "track-arun-1",
      title: "Snowfall",
      artist: "Øneheart, reidenshi",
      album: "Snowfall",
      albumArt: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/track/4xF4x2G0vggMuBu1kdAnW2",
      embedUri: "https://open.spotify.com/embed/track/4xF4x2G0vggMuBu1kdAnW2?utm_source=generator&theme=0",
      streamUrl: "https://ilm.stream12.radiohost.de/ilm_ilovechillhop_mp3-192",
      durationMs: 123000,
      genre: "Lofi Beats",
    },
    progressMs: 45000,
    lastUpdated: new Date().toISOString(),
  },
  "user-karthik": {
    userId: "user-karthik",
    isPlaying: true,
    track: {
      id: "track-karthik-1",
      title: "Awake",
      artist: "Tycho",
      album: "Awake",
      albumArt: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/track/2qxmye6gAegTMjLKEBoR7d",
      embedUri: "https://open.spotify.com/embed/track/2qxmye6gAegTMjLKEBoR7d?utm_source=generator&theme=0",
      streamUrl: "https://stream.radioparadise.com/mellow-128",
      durationMs: 283000,
      genre: "Ambient Electronic",
    },
    progressMs: 198000,
    lastUpdated: new Date().toISOString(),
  },
};

export const CURATED_FOCUS_STATIONS: FocusStation[] = [
  {
    id: "station-lofi",
    title: "Lofi Girl Study Session",
    description: "Peaceful chillhop beats to relax, study, and code to.",
    genre: "Lofi Chill",
    coverArt: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=300&auto=format&fit=crop&q=80",
    track: {
      id: "track-station-lofi",
      title: "Lofi Study Session 2026",
      artist: "Lofi Girl",
      album: "Beats to Study To",
      albumArt: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/playlist/0vvXsWCC9xrXsKd4FyS8kM",
      embedUri: "https://open.spotify.com/embed/playlist/0vvXsWCC9xrXsKd4FyS8kM?utm_source=generator&theme=0",
      streamUrl: "https://ilm.stream12.radiohost.de/ilm_ilovechillhop_mp3-192",
      genre: "Lofi Beats",
    },
  },
  {
    id: "station-synthwave",
    title: "Synthwave Coding Lounge",
    description: "Retrowave & cyberpunk energy for late night debugging.",
    genre: "Synthwave",
    coverArt: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
    track: {
      id: "track-station-synthwave",
      title: "Synthwave Cyberpunk Pulse",
      artist: "Kavinsky & Friends",
      album: "Night Drive Collection",
      albumArt: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DXdLEN7aqioXM",
      embedUri: "https://open.spotify.com/embed/playlist/37i9dQZF1DXdLEN7aqioXM?utm_source=generator&theme=0",
      streamUrl: "https://ilm.stream35.radiohost.de/ilm_ilovesugarradio_mp3-192",
      genre: "Synthwave",
    },
  },
  {
    id: "station-piano",
    title: "Peaceful Piano & Flow State",
    description: "Delicate minimalist piano for uninterrupted flow.",
    genre: "Classical / Piano",
    coverArt: "https://images.unsplash.com/photo-1520523839898-5071270438a3?w=300&auto=format&fit=crop&q=80",
    track: {
      id: "track-station-piano",
      title: "Nuvole Bianche",
      artist: "Ludovico Einaudi",
      album: "Una Mattina",
      albumArt: "https://images.unsplash.com/photo-1520523839898-5071270438a3?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX4sWSpwq3LiO",
      embedUri: "https://open.spotify.com/embed/playlist/37i9dQZF1DX4sWSpwq3LiO?utm_source=generator&theme=0",
      streamUrl: "https://stream.radioparadise.com/mellow-128",
      genre: "Piano Flow",
    },
  },
  {
    id: "station-deepfocus",
    title: "Deep Focus Soundscapes",
    description: "Atmospheric ambient textures for high-cognition problems.",
    genre: "Ambient",
    coverArt: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&auto=format&fit=crop&q=80",
    track: {
      id: "track-station-deepfocus",
      title: "Time (Deep Focus Edit)",
      artist: "Hans Zimmer",
      album: "Interstellar Suite",
      albumArt: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DWZeKCadgRdKQ",
      embedUri: "https://open.spotify.com/embed/playlist/37i9dQZF1DWZeKCadgRdKQ?utm_source=generator&theme=0",
      streamUrl: "https://stream.radioparadise.com/mellow-128",
      genre: "Deep Focus",
    },
  },
  {
    id: "station-techno",
    title: "Brain Food / Fast BPM Sprint",
    description: "Hypnotic electronic tempo for rapid development sprints.",
    genre: "Techno / Electronic",
    coverArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80",
    track: {
      id: "track-station-techno",
      title: "Fast Cadence Sprint Beats",
      artist: "Electronic Lab",
      album: "Brain Food Mix",
      albumArt: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&auto=format&fit=crop&q=80",
      spotifyUrl: "https://open.spotify.com/playlist/37i9dQZF1DX3PFDVr0Cu2l",
      embedUri: "https://open.spotify.com/embed/playlist/37i9dQZF1DX3PFDVr0Cu2l?utm_source=generator&theme=0",
      streamUrl: "https://ilm.stream35.radiohost.de/ilm_ilovesugarradio_mp3-192",
      genre: "Electronic",
    },
  },
];

export const INITIAL_FOCUS_ROOM: FocusRoom = {
  meetUrl: DEFAULT_MEET_URL,
  activeMemberIds: ["user-nova", "user-rahul", "user-arun"],
  isGroupListening: true,
  hostTrack: INITIAL_SPOTIFY_PRESENCES["user-nova"].track,
  pomodoro: {
    isActive: false,
    mode: "focus",
    timeLeftSeconds: 25 * 60,
    durationSeconds: 25 * 60,
    sessionsCompleted: 3,
  },
};
